org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.builtInKotlin=true
android.newDsl=true
android.dependency.useConstraints=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
